const MOCK_COURSES = [
	{
		average_rating: 4,
		category: "",
		company: "",
		company_logo: "",
		id: 1,
		reviews_count: 25,
		title: "First course",
	},
	{
		average_rating: 4,
		category: "",
		company: "",
		company_logo: "",
		id: 2,
		reviews_count: 25,
		title: "First course",
	},
	{
		average_rating: 4,
		category: "",
		company: "",
		company_logo: "",
		id: 3,
		reviews_count: 25,
		title: "First course",
	},
	{
		average_rating: 4,
		category: "",
		company: "",
		company_logo: "",
		id: 4,
		reviews_count: 25,
		title: "First course",
	},
	{
		average_rating: 4,
		category: "",
		company: "",
		company_logo: "",
		id: 5,
		reviews_count: 25,
		title: "First course",
	},
	{
		average_rating: 4,
		category: "",
		company: "",
		company_logo: "",
		id: 6,
		reviews_count: 25,
		title: "First course",
	},
	{
		average_rating: 4,
		category: "",
		company: "",
		company_logo: "",
		id: 7,
		reviews_count: 25,
		title: "First course",
	},
	{
		average_rating: 4,
		category: "",
		company: "",
		company_logo: "",
		id: 8,
		reviews_count: 25,
		title: "First course",
	},
];

export { MOCK_COURSES };
