export { AuthPage } from "./auth/index";
export { CompaniesListPage } from "./companies-list-page/index";
export { CompanyDetailsPage } from "./company-details-page/index";
export { CourseDetailsPage } from "./course-details-page";
export { HomePage } from "./home-page/index";
export { ModeratorsPage } from "./moderators-page/index";
export { PrivacyPolicy } from "./privacy-policy";
export { UserRequests } from "./user-requests/index";
export { UserReviews } from "./user-reviews/index";
