const MOCK_COURSES = [
  {  id: 1,
    title: "First course",
    company_logo: '',
    average_rating: 4,
    reviews_count: 25,
    category: '', 
    company: '', 
  },
  {  id: 2,
    title: "First course",
    company_logo: '',
    average_rating: 4,
    reviews_count: 25,
    category: '', 
    company: '', 
  },
  {  id: 3,
    title: "First course",
    company_logo: '',
    average_rating: 4,
    reviews_count: 25,
    category: '', 
    company: '', 
  },
  {  id: 4,
    title: "First course",
    company_logo: '',
    average_rating: 4,
    reviews_count: 25,
    category: '', 
    company: '', 
  },
  {  id: 5,
    title: "First course",
    company_logo: '',
    average_rating: 4,
    reviews_count: 25,
    category: '', 
    company: '', 
  },
  {  id: 6,
    title: "First course" ,
    company_logo: '',
    average_rating: 4,
    reviews_count: 25,
    category: '', 
    company: '', 
  },
  {  id: 7,
    title: "First course",
    company_logo: '',
    average_rating: 4,
    reviews_count: 25,
    category: '', 
    company: '', 
  },
  {  id: 8,
    title: "First course",
    company_logo: '',
    average_rating: 4,
    reviews_count: 25,
    category: '', 
    company: '', 
  },
];

export { MOCK_COURSES };