enum IconName {
	ARROW_DOWN = "arrowDown",
	ARROW_LEFT_LONG = "arrowLeftLong",
	ARROW_RIGHT = "arrowRight",
	ARROW_RIGHT_LONG = "arrowRightLong",
	ARROW_RIGHT_WIDE = "arrowRightWide",
	ARROW_TOP = "arrowUp",
	BUILDING = "building",
	DOLLAR_SIGN = "dollarSign",
	EMAIL = "email",
	FACEBOOK = "facebook",
	GLOBE = "globe",
	LINKEDIN = "linkedin",
	LIST_VIEW = "listView",
	LOCATION = "location",
	MINUS = "minus",
	PEOPLE = "people",
	PHONE = "phone",
	PLUS = "plus",
	SEARCH = "search",
	SHIELD_TICK = "shieldTick",
	SORT = "sort",
	TABLE_VIEW = "tableView",
	XRP = "xrp",
	YOUTUBE = "youtube",
}

export { IconName };
