enum IconName {
	ARROW_DOWN = "arrowDown",
	ARROW_LEFT_LONG = "arrowLeftLong",
	ARROW_RIGHT = "arrowRight",
	ARROW_RIGHT_LONG = "arrowRightLong",
	ARROW_RIGHT_WIDE = "arrowRightWide",
	ARROW_TOP = "arrowUp",
	AUDIENCE = "audience",
	BANK = "bank",
	EMAIL = "email",
	FACEBOOK = "facebook",
	GLOBAL = "global",
	LINKEDIN = "linkedin",
	LIST_VIEW = "listView",
	LOCATION = "location",
	MINUS = "minus",
	PHONE = "phone",
	PLUS = "plus",
	PRICE = "price",
	SEARCH = "search",
	SHIELD_TICK = "shieldTick",
	SHIELD_TICK_GREEN = "shieldTickGreen",
	SORT = "sort",
	STAR = "star",
	TABLE_VIEW = "tableView",
	TEACHER = "teacher",
	XRP = "xrp",
	YOUTUBE = "youtube",
}

export { IconName };
